//
//  HomePresenter.swift
//  Go-K Teste
//
//  Created by Junior Silva on 07/10/20.
//  Copyright (c) 2020 Junior Silva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
// This tag below is used to create the testable files from the Cuckoo pod
// CUCKOO_TESTABLE

import UIKit

protocol HomePresentationLogic {
    func reloadTableView()
    func stopsActivityIndicator()
    func presentSelectedSpotlight()
    func presentSelectedCash()
    func presentSelectedProduct()
    func presentEmptyState()
}

class HomePresenter: HomePresentationLogic {
    weak var viewController: HomeDisplayLogic?

    func reloadTableView() {
        viewController?.reloadTableView()
    }
    
    func stopsActivityIndicator() {
        viewController?.stopsActivityIndicator()
    }
    
    func presentSelectedSpotlight() {
        viewController?.displaySelectedSpotlight()
    }
    
    func presentSelectedCash() {
        viewController?.displaySelectedCash()
    }
    
    func presentSelectedProduct() {
        viewController?.displaySelectedProduct()
    }
    
    func presentEmptyState() {
        viewController?.displayEmptyState()
    }
}
