//
//  HomeRouter.swift
//  Go-K Teste
//
//  Created by Junior Silva on 07/10/20.
//  Copyright (c) 2020 Junior Silva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic {
    func routeToSelectedSpotlight()
    func routeToSelectedCash()
    func routeToSelectedProduct()
}

protocol HomeDataPassing {
    var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing {
    weak var viewController: HomeViewController?
    var dataStore: HomeDataStore?
    
    func routeToSelectedSpotlight() {
        let vc = DetailViewController()
        guard let destinationDataStore = vc.router?.dataStore else { return }
        var destinationDS = destinationDataStore
        passSpotlightDataToDetail(source: dataStore!, destination: &destinationDS)
        viewController?.present(vc, animated: true)
    }
    
    func passSpotlightDataToDetail(source: HomeDataStore, destination: inout DetailDataStore) {
        destination.selectedSpotlight = source.selectedSpotlight
    }
    
    func routeToSelectedCash() {
        let vc = DetailViewController()
        guard let destinationDataStore = vc.router?.dataStore else { return }
        var destinationDS = destinationDataStore
        passCashDataToDetail(source: dataStore!, destination: &destinationDS)
        viewController?.present(vc, animated: true)
    }
    
    func passCashDataToDetail(source: HomeDataStore, destination: inout DetailDataStore) {
        destination.selectedCash = source.selectedCash
    }

    func routeToSelectedProduct() {
        let vc = DetailViewController()
        guard let destinationDataStore = vc.router?.dataStore else { return }
        var destinationDS = destinationDataStore
        passProductDataToDetail(source: dataStore!, destination: &destinationDS)
        viewController?.present(vc, animated: true)
    }
    
    func passProductDataToDetail(source: HomeDataStore, destination: inout DetailDataStore) {
        destination.selectedProduct = source.selectedProduct
    }
    
}
