//
//  HomeRouter.swift
//  Go-K Teste
//
//  Created by Junior Silva on 07/10/20.
//  Copyright (c) 2020 Junior Silva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic {
    func routeToSelectedItem()
}

protocol HomeDataPassing {
    var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing {
    weak var viewController: HomeViewController?
    var dataStore: HomeDataStore?

    func routeToSelectedItem() {
        let vc = DetailViewController()
        var destinationDS = vc.router!.dataStore!
        passDataToDetail(source: dataStore!, destination: &destinationDS)
        viewController?.present(vc, animated: true)
    }
    
    func passDataToDetail(source: HomeDataStore, destination: inout DetailDataStore) {
        destination.selectedItem = source.selectedItem
    }
}
