//
//  HomeWorker.swift
//  Go-K Teste
//
//  Created by Junior Silva on 07/10/20.
//  Copyright (c) 2020 Junior Silva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
// This tag below is used to create the testable files from the Cuckoo pod
// CUCKOO_TESTABLE

import Foundation
import PromiseKit

protocol HomeNetworkProtocol {
    func searchList() -> Promise<Home.Response>
}

class HomeWorker: HomeNetworkProtocol {
    
    let networkProvider = NetworkProvider.shared
    
    func searchList() -> Promise<Home.Response> {
        networkProvider.request(.searchList())
    }
}
