//
//  HomeModels.swift
//  Go-K Teste
//
//  Created by Junior Silva on 07/10/20.
//  Copyright (c) 2020 Junior Silva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home {
    struct Response: Codable {
        var spotlight: [Spotlight]?
        var products: [Product]?
        var cash: Cash?
    }
}

struct Spotlight: Codable {
    let title: String
    let image: String
    let description: String
    
    enum CodingKeys: String, CodingKey {
        case title = "name"
        case image = "bannerURL"
        case description
    }
}

struct Product: Codable {
    let title: String
    let image: String
    let description: String
    
    enum CodingKeys: String, CodingKey {
        case title = "name"
        case image = "imageURL"
        case description
    }
}

struct Cash: Codable {
    let title: String
    let image: String
    let description: String
    
    enum CodingKeys: String, CodingKey {
        case title
        case image = "bannerURL"
        case description
    }
}

