//
//  DetailPresenter.swift
//  Go-K Teste
//
//  Created by Junior Silva on 07/10/20.
//  Copyright (c) 2020 Junior Silva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
// This tag below is used to create the testable files from the Cuckoo pod
// CUCKOO_TESTABLE

import UIKit

protocol DetailPresentationLogic {
    func presentEmptyState()
    func presentSelectedSpotlight(_ selectedItem: Spotlight?)
    func presentSelectedCash(_ selectedItem: Cash?)
    func presentSelectedProduct(_ selectedItem: Product?)
}

class DetailPresenter: DetailPresentationLogic {
    weak var viewController: DetailDisplayLogic?
    
    func presentSelectedSpotlight(_ selectedItem: Spotlight?) {
        viewController?.displaySelectedSpotlight(selectedItem)
    }
    
    func presentSelectedCash(_ selectedItem: Cash?) {
        viewController?.displaySelectedCash(selectedItem)
    }
    
    func presentSelectedProduct(_ selectedItem: Product?) {
        viewController?.displaySelectedProduct(selectedItem)
    }
    
    func presentEmptyState() {
        viewController?.displayEmptyState()
    }
    
}
